# Generated by Django 4.1 on 2022-12-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='tipe',
            field=models.CharField(choices=[('SENSITIVE', 'SENSITIVE'), ('OILY', 'OILY'), ('NORMAL', 'NORMAL'), ('ACNE-PRONE', 'ACNE-PRONE'), ('DRY', 'DRY'), ('ALL-SKIN', 'ALL-SKIN')], max_length=200, null=True),
        ),
    ]
