# Generated by Django 4.1 on 2022-12-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_reviewmodel_likes_reviewmodel_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='slug',
        ),
    ]
