# Generated by Django 4.1 on 2022-12-09 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=200, null=True)),
                ('isi_review', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tipe', models.CharField(choices=[('SENSITIVE', 'SENSITIVE'), ('OILY', 'OILY'), ('NORMAL', 'NORMAL'), ('ACNE-PRONE', 'ACNE-PRONE'), ('DRY', 'DRY'), ('ALL-SKIN', 'ALL-SKIN')], max_length=200, null=True)),
                ('likes', models.ManyToManyField(related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
