# Generated by Django 4.1.3 on 2022-12-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdisplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skincareitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_mosturizer', models.ManyToManyField(to='productdisplay.skincareitem')),
            ],
        ),
    ]
