# Generated by Django 4.1.3 on 2022-12-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productdisplay', '0002_alter_skincareitem_name_alter_tags_name_display'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Display',
        ),
    ]
